apiVersion: v1
kind: Pod
metadata:
  name: practice1
  namespace: docker-practice
  labels:
    app: docker-practice
    version: v1
spec:
  containers:
    - name: web
      image: practice1
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 8083
          protocol: TCP
  terminationGracePeriodSeconds: 60